### ISSUE TITLE
Only getting ~1k clips

### ISSUE THREAD

**Issue by CodeSpent** [HugoJF/twitch-clip-downloader#3]
I see your warning regarding only getting ~1,000 clips and this is the behavior of simply asking for the clips of a user. To mitigate this, what you can do is request between time frames using `started_at` and `ended_at`.

The seconds on a timestamp will be ignored, & as well Twitch rounds to the nearest 10 minutes when querying for the range.

The default for `ended_at` is 7 days from the `started_at` timestamp, however, I found that the only way to not miss clips is handle on a 1-3 day range.

I've tested this technique with summit1g and using the default 7 day range resulted in 4,116 clips, where using a 3 day range resulted in 13,612 clips (1 day range was also 13, 612).

I hope this information helps you in getting your tool capable of getting all clips!

**Comment by HugoJF** [comment]
Oh that's VERY interesting. I did not realize that v5 was deprecated already, instead of calling v6, they decided to call "New Twitch API". Only now that you mention the `ended_at` and `started_at` parameters that I figured where they are.

Thank you for sharing this, I was exploring using the client OAuth token and using their internal API to fetch everything, but that is too hacky/bleh for me.

Once I have some free time I'll update the tool, thanks again!

**Comment by HugoJF** [comment]
New API was implemented on 9779ac33efe85ac2f61cee0f7ab5e72d55933f9f

After testing on summit1g, this tool managed to fetch 163k clips since 2016. I have no idea is there is a way to check if this is correct, but on smaller channels, it's spot on.
