### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by camjac251** [HugoJF/twitch-clip-downloader#32]
I am having difficulty running a full channel archive of clips. Tried to get it to run through on two different instances (VPS on cloud providers, 4GB ram each) but it failed both times at around the same page number. I am trying the username `hasanabi` but it doesn't get past page 38, it would seem. I tried this on node 10, 12 and I believe 14, all had some weird issues, like this.

Attaching hopefully the stack trace
```
<--- Last few GCs --->

[48381:0x9819b0]  3065294 ms: Mark-sweep 1221.7 (1284.7) -> 1221.7 (1253.7) MB, 432.2 / 0.0 ms  (average mu = 0.400, current mu = 0.000) last resort GC in old space requested
[48381:0x9819b0]  3065727 ms: Mark-sweep 1221.7 (1253.7) -> 1221.7 (1253.7) MB, 432.7 / 0.0 ms  (average mu = 0.246, current mu = 0.000) last resort GC in old space requested
```
```
<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3e3a60c53601]
Security context: 0x1408f4c2ee11 <JSObject>
    1: byteLength(aka byteLength) [0x16c33c197e89] [buffer.js:~508] [pc=0x3e3a612623f7](this=0x20a881e825d9 <undefined>,string=0x07cc5197a6a1 <Very long string[114600168]>,encoding=0x1408f4c72a51 <String[4]: utf8>)
    2: arguments adaptor frame: 3->2
    3: fromString(aka fromString) [0x16c33c197d49] [buffer.js:~333] [pc=0x3e3a61264890](this=0x20a881e825d9 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x7f05f251746c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7f05f25174b5  [/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7f05f2743e6a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7f05f27440e1 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7f05f2adec66  [/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7f05f2af2a37 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7f05f2abea8d v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map*, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7f05f2ac7178 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7f05f2c072ad v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x7f05f274e2d8 v8::String::Utf8Length() const [/lib/x86_64-linux-gnu/libnode.so.64]
11: 0x7f05f2532115  [/lib/x86_64-linux-gnu/libnode.so.64]
12: 0x3e3a60c53601 
Aborted (core dumped)
```
[full-log-twitch.txt](https://github.com/HugoJF/twitch-clip-downloader/files/6209020/full-log-twitch.txt)

**Comment by HugoJF** [comment]
Hmm, looking at the logs it seems like it's happening at around 200k clips, which is lower than what I could get from previous versions of this tool (afaik I managed to get 300k at some point with no issues).

I'm not sure if there are obvious memory hogs I could fix, but I'll play around so see what I can get done.

In the mean time, since you have plenty more RAM available, I suggest bumping the heap size while I work this out.

EDIT1: I've been attempting to reproduce this problem in my machine with Hasan's channel and realized that the period splitting logic is going crazy splitting a whole month into <3h periods. Since this is a recursive call I imagine alot of variables are being held in memory until the code finds a period small enough to get <500 clips.

EDIT2: Just noticed a giant mistake in the caching system. Instead of each period file storing clips found ONLY in that period, it saved every clip that was found at that moment. This caused the /cache directory to grow beyond 10GB. Because of this CPU usage was VERY high, memory usage was higher than usual (the main problem was elsewhere), and my SSD to be suffocated to death. A fix in being tested right now.

**Comment by HugoJF** [comment]
Can you please check if the most recent version fixes your problem?

**Comment by camjac251** [comment]
Hey sorry for the delay. It works perfectly. Was able to find 433,304 clips and save to the meta file.

Thank you very much
