### ISSUE TITLE
Downloading personal clips

### ISSUE THREAD

**Issue by BooRadley976** [HugoJF/twitch-clip-downloader#9]
Hello. I am very poor at programming, so do not scold me!

Is there a technical possibility to implement a similar script, but for clips made by a specific user (for example, by me)?
The fact is, I want to download my clips, but the limit of 1000 clips prevents me from doing this.

**Comment by HugoJF** [comment]
Just checked API reference for v5 and the current version, and I don't see any field that would allow one to get clips by the creator ID.

That said, it's possible, you can inspect the network requests made when you scroll through the clips dashboard, and use that endpoint (you need to extract 1 or 2 cookies to pass them as request headers). That said, it's not a public endpoint, and it's made to be used internally, so I don't think I'll ever support this.

You can probably use TamperMonkey to fetch a list of clips, and then pass them to YoutubeDL.

I'll be closing this issue since it's not related to the project, but feel free to continue the discussion if you have any questions regarding this.
